pipeline {
    agent {
        any {
            image 'ruby'
        }
    }

    stages {
        stage('Prep') {
            steps {
               sh 'bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cucumber'
            }
        }
    }
}
