pipeline {
    agent {
        any {
            image 'ruby'
        }
    }

    stages {
        stage('Prep') {
            steps {
               sh 'cd web && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cd web && cucumber -p jenkins'
            }
        }
        stage('UAT') {
            steps {
                echo 'Aguardando testes de aceitação.'
                input message: 'Podemos ir à produção?'
            }
        }
        stage('Prod') {
            steps {
                echo 'WebApp pronto para produção :)'
            }
        }
    }
    post {
        always {
            echo 'todo'
        }
    }
}
